MvcStok/MvcStok/Controllers/MusteriController.cs
using MvcStok.Models.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            //var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
            var degerler = from d in db.TBLMUSTERILER select d;

            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
        }




        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            { return View(); }

            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();

        }

        public ActionResult Sil(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", musteri);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Müşteriler";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index","Musteri",FormMethod.Get))
            {
                <p class="text-info">Aranacak Müşteri Adı: @Html.TextBox("p") <input type="submit" value="Ara" class="btn btn-default" /></p>
                
            }
<table class="table table-bordered">
    <tr>
        <th>MUSTERI ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT</th>
    </tr>

    <tbody>
        
        @foreach(var musteri in Model)
            {
                <tr>
                    <th>@musteri.MUSTERIID</th>
                    <td>@musteri.MUSTERIAD</td>
                    <td>@musteri.MUSTERISOYAD</td>
                    <td><a href="/Musteri/SIL/@musteri.MUSTERIID" class="btn btn-danger">SİL</a></td>
                    <td><a href="/Musteri/MusteriGetir/@musteri.MUSTERIID" class="btn btn-warning">GÜNCELLE</a></td>
                    <td>@Html.ActionLink("SİL BUTONU","SIL",new {id=musteri.MUSTERIID}, new {@class="btn btn-danger", onclick="return confirm('Gerçekten silmek istiyor musunuz?')"})</td>
                </tr>
            }
    </tbody>
</table>

<a href="/Musteri/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{

    <div>
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERISOYAD)
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <br />

    <div>
        <button class="btn btn-warning">
            Güncelle
        </button>
    </div>
}

MvcStok/MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post">
    <div class="form-group">
        <label for="exampleInputName">Ad</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })
    </div>
    <div class="form-group">
        <label for="exampleInputSurname">Soyad</label>
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERISOYAD, "", new { @style = "color:red" })
    </div>

    <button type="submit" class="btn btn-primary" id="btn1">Ekle</button>

    <script>
        $('#btn1').click(function () {
            alert("Müşteri ekleme işlemi yapıldı...!");
        });
    </script>
</form>