MvcStok/MvcStok/Controllers/UrunController.cs
using MvcStok.Models.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun

        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }

        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler =
                (
                from i in db.TBLKATEGORILER.ToList()
                select new SelectListItem
                {
                    Text = i.KATEGORIAD,
                    Value = i.KATEGORIID.ToString()
                }
                ).ToList();
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            List<SelectListItem> degerler =
         (
         from i in db.TBLKATEGORILER.ToList()
         select new SelectListItem
         {
             Text = i.KATEGORIAD,
             Value = i.KATEGORIID.ToString()
         }
         ).ToList();
            ViewBag.dgr = degerler;
            return View(urun);
        }

        public ActionResult Guncelle(TBLURUNLER p1)
        {
            var urun = db.TBLURUNLER.Find(p1.URUNID);
            urun.URUNAD = p1.URUNAD;
            urun.MARKA = p1.MARKA;
            urun.STOK = p1.STOK;
            urun.FIYAT = p1.FIYAT;
            //urun.URUNKATEGORI = p1.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Urun/Index.cshtml
@{
    ViewBag.Title = "Urunler";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using MvcStok.Models.Entity

@model List<TBLURUNLER>


<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>MARKASI</th>
            <th>KATEGORİ</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var urun in Model)
            {
                <tr>
                    <th>@urun.URUNID</th>
                    <td>@urun.URUNAD</td>
                    <td>@urun.MARKA</td>
                    <td>@urun.TBLKATEGORILER.KATEGORIAD</td>
                    <td>@urun.FIYAT₺</td>
                    <td>@urun.STOK</td>
                    <td><a href="/URUN/SIL/@urun.URUNID" class="btn btn-danger">SİL</a></td>
                    <td><a href="/URUN/UrunGetir/@urun.URUNID" class="btn btn-warning">GÜNCELLE</a></td>


                </tr>
            }

    </tbody>
</table>

<a href="/Urun/UrunEkle/" class="btn btn-primary">YENİ ÜRÜN EKLE</a>

<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js">

</script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.13.4/i18n/tr.json"></script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

<script >
    $('#tbl1').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
        }
    });
</script>

MvcStok/MvcStok/Views/Urun/UrunEkle.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post">
    <div class="form-group">
        <label for="exampleInputName">Ad</label>
        <input type="text" class="form-control" id="exampleInputName" name="URUNAD" placeholder="Ad giriniz" required maxlength="10">

    </div>
    <div class="form-group">
        <label for="exampleInputSurname">Marka</label>
        <input type="text" class="form-control" id="exampleInputSurname" name="MARKA" placeholder="Marka Giriniz" required maxlength="10">
    </div>

    <div class="form-group">
        <label for="kategoriler">Kategori</label>
        @Html.DropDownListFor(
       m=>m.TBLKATEGORILER.KATEGORIID,
       (List<SelectListItem>) ViewBag.dgr,
       new {@class="form-control"}
       )
    </div>

    <div class="form-group">
        <label for="exampleInputSurname">Fiyat</label>
        <input type="number" min="1" step="any" class="form-control" id="exampleInputSurname" name="FIYAT" placeholder="Fiyat Giriniz">
    </div>

    <div class="form-group">
        <label for="exampleInputSurname">Stok</label>
        <input type="number" class="form-control" id="exampleInputSurname" name="STOK" placeholder="Stok Giriniz">
    </div>



    <button type="submit" class="btn btn-primary">Ekle</button>
</form>

MvcStok/MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBLURUNLER

@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{

    <div>
        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>)ViewBag.dgr, new {@class="form-control"})
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })
    </div>
    <br />

    <div>
        <button class="btn btn-warning">
            Güncelle
        </button>
    </div>
}